shoesbox/shoesbox-be

src/main/java/com/shoesbox/comment/Comment.java
src/main/java/com/shoesbox/comment/CommentController.java
src/main/java/com/shoesbox/comment/CommentResponseDto.java
src/main/java/com/shoesbox/comment/CommentService.java
src/main/java/com/shoesbox/post/Post.java
src/main/java/com/shoesbox/post/PostRepository.java
src/main/java/com/shoesbox/post/PostResponseDto.java
src/main/java/com/shoesbox/post/PostService.java

Comment와 Post 연관관계 설정

---

src/main/java/com/shoesbox/domain/comment/Comment.java
src/main/java/com/shoesbox/domain/comment/CommentController.java
src/main/java/com/shoesbox/domain/comment/CommentRequestDto.java
src/main/java/com/shoesbox/domain/comment/CommentResponseDto.java
src/main/java/com/shoesbox/domain/comment/CommentService.java
src/main/java/com/shoesbox/domain/member/MemberService.java
src/main/java/com/shoesbox/domain/post/Post.java
src/main/java/com/shoesbox/domain/post/PostController.java
src/main/java/com/shoesbox/domain/post/PostService.java
src/main/java/com/shoesbox/domain/post/dto/PostListResponseDto.java
src/main/java/com/shoesbox/domain/post/dto/PostRequestDto.java
src/main/java/com/shoesbox/global/config/SecurityConfig.java

- 버그 및 기능 개선
<br>
- request에 불필요한 값이 들어있거나
- response에 필요한 값이 없는 경우 수정
- 로그인한 사용자만 글 보기가 가능하게 수정
Related to: #24
<br>
-
<br>
close #24

fix: Fix request and response value, authorization

---

src/main/java/com/shoesbox/domain/post/Post.java
src/main/java/com/shoesbox/domain/post/PostController.java
src/main/java/com/shoesbox/domain/post/PostRepository.java
src/main/java/com/shoesbox/domain/post/PostService.java

post api 추가
#6
- 게시물 상세조회, 수정, 삭제 구현
<br>
- post의 controller, service가 주로 변경되었습니다. 상세조회, 수정, 삭제 기능이 추가되었습니다.
<br>
- 보안 요소를 살펴 보는 것이 중요할 것 같습니다. 
<br>

Feat : Post 수정 삭제 추가

---

src/main/java/com/shoesbox/domain/member/MemberController.java
src/main/java/com/shoesbox/domain/member/MemberService.java

- 회원 탈퇴 기능 추가
<br>
- 회원 탈퇴 기능 추가
<br>
-
<br>
close #40

feat: Add delete account

---

src/main/java/com/shoesbox/domain/auth/RefreshToken.java
src/main/java/com/shoesbox/domain/auth/TokenDto.java
src/main/java/com/shoesbox/domain/member/MemberController.java
src/main/java/com/shoesbox/domain/member/MemberService.java
src/main/java/com/shoesbox/global/security/CustomUserDetails.java
src/main/java/com/shoesbox/global/security/CustomUserDetailsService.java
src/main/java/com/shoesbox/global/security/jwt/TokenProvider.java

- 토큰 발급 과정 개선
<br>
- 토큰 발급, 재발급 과정 개선
- 코드 가독성 개선
- 잘못된 변수명(ex. userId) 수정
- 불필요한 getter 제거
- 반환되는 TokenDto 객체에 nickname 포함
- CustomUserDetails 가 Builder 를 사용
- 토큰 재발급 메서드 명 renewToken -> refreshToken 변경
<br>
-
<br>
close #43

refactor: Refactor issue jwt

---

src/main/java/com/shoesbox/domain/member/MemberService.java

- 회원 프로필 이미지 기본값 지정
<br>
- 회원 프로필 이미지 기본값 지정
<br>
-
<br>
close #42

feat: Add default profile image

---

src/main/java/com/shoesbox/domain/member/MemberController.java
src/main/java/com/shoesbox/domain/member/MemberService.java
src/main/java/com/shoesbox/domain/member/dto/MemberInfoResponseDto.java
src/main/java/com/shoesbox/domain/member/dto/MemberInfoUpdateDto.java
src/main/java/com/shoesbox/domain/post/PostService.java

- 회원 정보 수정 기능 추가
<br>
- 회원 정보 수정 기능 추가
<br>
-
<br>
close #46

feat: Add update member info

---

src/main/java/com/shoesbox/domain/member/MemberService.java
src/main/java/com/shoesbox/domain/post/PostService.java
src/main/java/com/shoesbox/domain/post/dto/PostResponseDto.java

- 게시글 반환값 수정 및 예외처리
<br>
- fix author -> nickname
- add memberId
- add exception
<br>
-
<br>
close #50

refactor: Refactor post response and exception

---

src/main/java/com/shoesbox/domain/post/Post.java
src/main/java/com/shoesbox/domain/post/PostController.java
src/main/java/com/shoesbox/domain/post/PostService.java
src/main/java/com/shoesbox/domain/post/dto/PostResponseDto.java

- 게시글 작성 조건 추가 및 반환값 수정
<br>
- 게시글 작성 시 무조건 이미지 파일을 1개 이상 첨부해야 함
- 게시글 상세보기의 이미지 url 목록 변수 이름이 imageUrls로 변경
- 게시글 상세보기에 있던 images 변수 삭제
<br>
-
<br>
close #50

refactor: Modify post response

---

src/main/java/com/shoesbox/domain/post/PostController.java
src/main/java/com/shoesbox/domain/post/PostRepository.java
src/main/java/com/shoesbox/domain/post/PostService.java

- 게시글 작성 수 제한
<br>
- controller, service에 게시글 작성 횟수 제한 부분 추가
<br>
- 코드
<br>

Fix: fix Post number limit

---

src/main/java/com/shoesbox/domain/member/MemberController.java
src/main/java/com/shoesbox/domain/member/MemberService.java

- 프로필 사진을 기본값으로 초기화하는 기능 추가
<br>
- 프로필 사진 초기화 api 추가
- "/api/members/reset"
<br>
-
<br>
close #70

feat: 회원 프로필 사진 초기화

---

src/main/java/com/shoesbox/ShoesBoxApplication.java
src/main/java/com/shoesbox/domain/comment/Comment.java
src/main/java/com/shoesbox/domain/comment/CommentController.java
src/main/java/com/shoesbox/domain/comment/CommentResponseDto.java
src/main/java/com/shoesbox/domain/comment/CommentService.java
src/main/java/com/shoesbox/domain/post/PostService.java

- 댓글에 작성자의 프로필 이미지 url 추가
<br>
- 댓글 엔티티 및 반환값에 작성자의 프로필 이미지 url 추가
<br>
-
<br>
close #74

feat: 댓글에 프로필 이미지 추가

---

src/main/java/com/shoesbox/domain/friend/FriendController.java
src/main/java/com/shoesbox/domain/friend/FriendRepository.java
src/main/java/com/shoesbox/domain/friend/FriendService.java

- 내가 요청한 친구도 조회/요청취소 할 수 있게 수정
<br>
- 친구 요청한 목록 추가
- 친구 요청 취소 기능 추가
- 일부 코드 리팩토링
<br>
- 버그
<br>

feat: Add Friend Request List

---

src/main/java/com/shoesbox/domain/post/Post.java
src/main/java/com/shoesbox/domain/post/PostController.java
src/main/java/com/shoesbox/domain/post/PostService.java

- 자유로운 글 수정
<br>
- 글 수정 방식을 PUT 에서 PATCH로 변경
- 이제 첨부 이미지, 글 제목, 본문 중 1개만 보내도 글 수정 가능
<br>
-
<br>
close #82

feat: Modify post update

---

src/main/java/com/shoesbox/domain/comment/CommentService.java

- 댓글 작성시 작성자가 현재 로그인한 유저가 아닌 게시글 작성자로 보이는 문제 수정
<br>
- 댓글 작성시 작성자에 현재 로그인한 유저가 들어가도록 수정
<br>
-
<br>

fix: Fix comment create

---

src/main/java/com/shoesbox/domain/friend/dto/FriendRequestDto.java
src/main/java/com/shoesbox/domain/friend/dto/FriendResponseListDto.java

- 누락된 dto 클래스 추가
<br>
-
<br>
-
<br>
close #91

fix: Fix friend dto

---

src/main/java/com/shoesbox/domain/post/PostService.java

- 권한 검증 로직 버그 수정
<br>
- 자기 자신인지, 친구 관계인지 검증하는 로직 버그 수정
<br>
-
<br>

fix: Fix get posts authorization bug

---

.github/workflows/deploy.yml
.github/workflows/gradle.yml
appspec.yml
build.gradle
scripts/start.sh
scripts/stop.sh

- CD 구현
<br>
- AWS IAM 인증
- 빌드파일을 S3 버킷 업로드
- 업로드한 빌드 파일을 EC2에 배포
<br>
-
<br>

feat: Add Code Deploy with AWS

---

src/main/java/com/shoesbox/domain/post/PostService.java

PATCH : Thumbnail Image Changed

---

.github/workflows/build.yml
.github/workflows/deploy.yml

- 빌드와 배포 workflow 분리
<br>
- deploy.yml에서 빌드 부분을 build.yml로 분리
- PR 시 배포 없이 build 테스트만 수행
- main에 push할 때 최종 배포 수행
<br>
-
<br>

feat: Add multi-stage deployments

---

scripts/stop.sh
src/main/java/com/shoesbox/domain/post/Post.java
src/main/java/com/shoesbox/domain/post/PostController.java
src/main/java/com/shoesbox/domain/post/PostService.java

- 댓글처럼 기존에 작성한 글의 작성자 닉네임 변경이 적용되도록 변경
<br>
- get post 시 post의 nickname이 아닌, member의 nickname을 가져옴.
<br>
-
<br>

update: 기존에 작성한 글의 작성자 닉네임 변경이 적용되도록 변경

---

src/main/java/com/shoesbox/domain/guest/GuestService.java

- 친구계정이 db에 없을 경우 자동으로 생성하는 로직 추가
<br>
- GuestService에서 친구 계정이 없을 경우 친구계정을 생성하는 로직 추가
<br>
-
<br>

Fix: Fix Guest Friend Account make auto

---

build.gradle
src/main/java/com/shoesbox/domain/guest/GuestService.java
src/main/java/com/shoesbox/domain/photo/S3Service.java
src/main/java/com/shoesbox/domain/photo/exception/ImageUploadFailureException.java
src/main/java/com/shoesbox/domain/post/PostController.java
src/main/java/com/shoesbox/domain/post/PostService.java
src/main/java/com/shoesbox/global/config/SecurityConfig.java
src/main/java/com/shoesbox/global/exception/RestExceptionHandler.java
src/main/resources/application.yml

- 이미지를 압축하여 트래픽 감소, 공간 절약 효과를 보기 위함
<br>
- 첨부 이미지와 썸네일을 WebP로 압축하는 기능 추가
- 기본 프로필 사진, 썸네일 모두 WebP로 교체
<br>
-
<br>

feat: 이미지 압축 기능 추가

---

src/main/java/com/shoesbox/domain/guest/GuestService.java
src/main/java/com/shoesbox/domain/member/MemberController.java
src/main/java/com/shoesbox/domain/member/MemberService.java
src/main/java/com/shoesbox/domain/post/PostService.java

- 기본 이미지 링크가 올바르게 들어가도록 수정
<br>
-
<br>
-
<br>

fix: 기본 이미지 링크가 잘못 들어가있는 버그 수정
